export const en = {
    nav: '整洁显示',
    openTitle: 'Open deliverables in built-in panel',
    openDescription: 'Off by default: chips and inline file mentions open in the system app. Turn this on to preview them in the right Sidebar, matching official chat. Reveal and folder actions still use the system file manager.',
    glassTitle: 'Translucent frosted glass',
    glassDescription: 'Off by default: reading chrome stays opaque, matching the current Host look. Turn this on to let wallpaper and skins show through the panel; path and count chips stay clear until hover or focus.',
    bubbleTitle: 'Message bubbles',
    bubbleDescription: 'On by default: final answers sit in a rounded bubble that separates them from the background, translucent in frosted-glass mode. Turn this off to lay answers flat on the page.',
    foldTitle: 'Auto-fold process',
    foldDescription: 'Default on: collapses earlier steps when new thoughts appear. Turn off to keep all thinking and tools expanded in full.',
    foldNone: 'Off',
    foldStandard: 'On',
    foldSummary: 'Summary',
    railTitle: 'Message rail',
    railDescription: 'On by default: a canvas navigation rail at the conversation edge — fish-eye hover with summaries, click to jump, current-turn highlight. Off: no rail in the reading view; the conversation view returns to the official rail.',
    railSide: 'Rail position',
    railSideLeft: 'Left edge',
    railSideRight: 'Right edge (mirrored)',
    railStyle: 'Rail style',
    railStyleBar: 'Lines',
    railStyleDot: 'Dots',
    railRingTitle: 'Rail sheen',
    railRingDescription: 'On by default (matches the store default): a soft white sheen laid beneath the current and hovered marks, keeping them readable over busy wallpapers.',
    takeoverTitle: 'Take over the official rail',
    takeoverDescription: 'On by default: in the conversation view this rail replaces the official right-edge TurnNavigator (hidden, not unmounted). Turn off to hand the conversation view back to the official rail — this rail yields there. The reading view always uses this rail. At narrow widths the harness auto-hides the official rail; this switch restores it when off.',
    colorBarTitle: 'Mark color',
    colorAccentTitle: 'Accent color',
    colorAuto: 'Auto',
    colorCustom: 'Custom',
    skillTitle: 'generative-mcpapps skill',
    skillInstalled: 'Installed',
    skillMissing: 'Not detected',
    skillPurpose: 'This install is for model auto-selection of MCP Apps. Reader already renders mcp-app fences when the model emits them.',
    skillPluginNote: 'Shipping the pack inside this plugin repository does not install it into the harness skill catalog.',
    skillInstall: 'Copy the whole generative-mcpapps folder (including references and examples) into .dsh/skills or .agents/skills — in your home or the project, you choose — then Re-check. There is no one-click install that works on every host.',
    skillRecheck: 'Re-check',
    skillChecking: 'Checking…',
    skillUnavailable: 'Could not query the host skill catalog. Copy into .dsh/skills or .agents/skills (home or project), then Re-check.',
};
export const zh = {
    nav: '整洁显示',
    openTitle: '在内置面板中打开产物',
    openDescription: '默认关闭：产物芯片和正文中的文件提及会用系统应用打开。打开后与官方对话一致，在右侧栏预览。访达 / 资源管理器中的显示与打开所在文件夹不受此开关控制。',
    glassTitle: '半透明毛玻璃',
    glassDescription: '默认关闭：阅读栏保持不透明，和现在的 Host 观感一致。打开后透出宿主壁纸与皮肤；路径、行数等标签静止时透明，悬停或聚焦才显出轮廓。',
    bubbleTitle: '消息气泡',
    bubbleDescription: '默认开启：最终回答放进圆角气泡，与页面背景区分；毛玻璃模式下呈半透明。关闭后回答平铺在页面上。',
    foldTitle: '自动折叠过程',
    foldDescription: '默认开启：新思考产生时自动折叠此前步骤。关闭后全程展开，完整保留原始思考与工具流。',
    foldNone: '关闭',
    foldStandard: '开启',
    foldSummary: '摘要',
    railTitle: '消息轨',
    railDescription: '默认开启：会话区边缘的 canvas 导航轨——鱼眼悬停看摘要、点击跳转、当前轮高亮。关闭后：阅读视图无轨，对话视图回到官方轨。',
    railSide: '显示位置',
    railSideLeft: '左缘',
    railSideRight: '右缘（镜像）',
    railStyle: '显示样式',
    railStyleBar: '横线',
    railStyleDot: '圆点',
    railRingTitle: '外圈柔光',
    railRingDescription: '默认开启：在当前轮与悬停轮的标记底下垫一层白色柔光，复杂壁纸上也能看清标记。',
    takeoverTitle: '接管官方消息轨',
    takeoverDescription: '默认开启：对话视图由本轨替换官方右缘 TurnNavigator（隐藏而非卸载）。关闭后对话视图交还官方轨，本轨在对话视图让位；阅读视图始终用本轨。窄宽度下宿主会自藏官方轨，关闭本开关时会一并恢复。',
    colorBarTitle: '标记色',
    colorAccentTitle: '强调色',
    colorAuto: '自动',
    colorCustom: '自定义',
    skillTitle: 'generative-mcpapps 技能',
    skillInstalled: '已安装',
    skillMissing: '未检测到',
    skillPurpose: '这项安装是为了让模型自动选用 MCP Apps。阅读页在模型写出 mcp-app 代码块时已经会渲染，不依赖该技能是否装进宿主。',
    skillPluginNote: '技能包只出现在本插件仓库里，并不等于当前 Agent 已经加载它。',
    skillInstall: '把完整的 generative-mcpapps 文件夹（含 references 与 examples）复制到 .dsh/skills 或 .agents/skills（家目录或项目目录，由你选），然后重新检测。没有在所有宿主上都可用的一键安装。',
    skillRecheck: '重新检测',
    skillChecking: '正在检测…',
    skillUnavailable: '无法查询宿主技能目录。请复制到 .dsh/skills 或 .agents/skills（家目录或项目），再重新检测。',
};
export const fr = {
    nav: 'Affichage épuré',
    openTitle: 'Ouvrir les livrables dans le panneau intégré',
    openDescription: 'Désactivé par défaut : les puces et les fichiers mentionnés s’ouvrent dans l’application système. Activez l’option pour les prévisualiser dans la barre latérale droite, comme dans le chat officiel. Révéler et ouvrir le dossier passent toujours par le gestionnaire de fichiers système.',
    glassTitle: 'Verre dépoli translucide',
    glassDescription: 'Désactivé par défaut : l’habillage de lecture reste opaque, fidèle au look actuel de l’hôte. Activez l’option pour laisser transparaître le fond d’écran et les thèmes ; les puces de chemin et de compteur ne se dessinent qu’au survol ou au focus.',
    bubbleTitle: 'Bulles de message',
    bubbleDescription: 'Activé par défaut : les réponses finales sont posées dans une bulle arrondie qui les détache du fond, translucide en mode verre dépoli. Désactivez pour afficher les réponses à plat sur la page.',
    foldTitle: 'Replier le processus',
    foldDescription: 'Activé par défaut : les étapes précédentes se replient dès qu’une nouvelle pensée apparaît. Désactivez pour garder tous les raisonnements et tous les outils dépliés.',
    foldNone: 'Désactivé',
    foldStandard: 'Activé',
    foldSummary: 'Résumé',
    railTitle: 'Rail des messages',
    railDescription: 'Activé par défaut : un rail de navigation en canvas au bord de la conversation — survol fisheye avec résumés, clic pour rejoindre un tour, tour active mis en évidence. Désactivé : pas de rail en vue lecture ; la vue conversation revient au rail officiel.',
    railSide: 'Position du rail',
    railSideLeft: 'Bord gauche',
    railSideRight: 'Bord droit (en miroir)',
    railStyle: 'Style du rail',
    railStyleBar: 'Traits',
    railStyleDot: 'Points',
    railRingTitle: 'Halo du rail',
    railRingDescription: 'Activé par défaut (conforme au réglage d’origine) : un doux halo blanc posé sous les repères actifs et survolés, pour rester lisibles sur les fonds d’écran chargés.',
    takeoverTitle: 'Remplacer le rail officiel',
    takeoverDescription: 'Activé par défaut : dans la vue de conversation, ce rail remplace le TurnNavigator officiel du bord droit (masqué, pas démonté). Désactivez pour rendre la vue de conversation au rail officiel — ce rail s’y efface. La vue de lecture utilise toujours ce rail. Aux petites largeurs le harnais masque le rail officiel de lui-même ; ce commutateur le restaure quand il est désactivé.',
    colorBarTitle: 'Couleur des repères',
    colorAccentTitle: 'Couleur d’accent',
    colorAuto: 'Auto',
    colorCustom: 'Personnalisée',
    skillTitle: 'Compétence generative-mcpapps',
    skillInstalled: 'Installée',
    skillMissing: 'Non détectée',
    skillPurpose: 'Cette installation sert à la sélection automatique des MCP Apps par le modèle. Le lecteur rend déjà les blocs mcp-app quand le modèle en produit.',
    skillPluginNote: 'Livrer le pack dans ce dépôt de plugin ne l’installe pas dans le catalogue de compétences de l’hôte.',
    skillInstall: 'Copiez le dossier generative-mcpapps complet (references et examples inclus) dans .dsh/skills ou .agents/skills — dans votre home ou dans le projet, à vous de choisir — puis relancez la vérification. Aucune installation en un clic ne fonctionne sur tous les hôtes.',
    skillRecheck: 'Revérifier',
    skillChecking: 'Vérification…',
    skillUnavailable: 'Impossible d’interroger le catalogue de compétences de l’hôte. Copiez dans .dsh/skills ou .agents/skills (home ou projet), puis revérifiez.',
};
export const de = {
    nav: 'Aufgeräumte Anzeige',
    openTitle: 'Ergebnisse im integrierten Panel öffnen',
    openDescription: 'Standardmäßig aus: Chips und Dateierwähnungen öffnen sich in der System-App. Einschalten, um sie wie im offiziellen Chat in der rechten Seitenleiste anzusehen. Das Anzeigen im Finder bzw. Explorer und das Öffnen des Ordners laufen weiterhin über den System-Dateimanager.',
    glassTitle: 'Mattiertes Milchglas',
    glassDescription: 'Standardmäßig aus: Die Leseleiste bleibt opak, passend zum bisherigen Host-Look. Einschalten, damit Hintergrundbild und Skins durchscheinen; Pfad- und Zähler-Chips bleiben unauffällig, bis man sie überfährt oder fokussiert.',
    bubbleTitle: 'Nachrichtenblasen',
    bubbleDescription: 'Standardmäßig ein: Finale Antworten liegen in einer abgerundeten Blase vor dem Hintergrund, im Milchglas-Modus halbtransparent. Ausschalten, um Antworten flach auf der Seite zu setzen.',
    foldTitle: 'Prozess automatisch einklappen',
    foldDescription: 'Standardmäßig ein: Ältere Schritte klappen sich ein, sobald neue Gedanken erscheinen. Ausschalten, um sämtliches Denken und alle Tools ausgeklappt zu lassen.',
    foldNone: 'Aus',
    foldStandard: 'Ein',
    foldSummary: 'Zusammenfassung',
    railTitle: 'Nachrichtenleiste',
    railDescription: 'Standardmäßig ein: eine Navigationsleiste aus Canvas am Rand des Gesprächs — Fischaugen-Hover mit Zusammenfassungen, Klick zum Springen, Hervorhebung des aktuellen Durchgangs. Aus: keine Leiste in der Leseansicht; die Konversationsansicht kehrt zur offiziellen Leiste zurück.',
    railSide: 'Position der Leiste',
    railSideLeft: 'Linker Rand',
    railSideRight: 'Rechter Rand (gespiegelt)',
    railStyle: 'Stil der Leiste',
    railStyleBar: 'Striche',
    railStyleDot: 'Punkte',
    railRingTitle: 'Sanfter Schimmer',
    railRingDescription: 'Standardmäßig ein (entspricht dem Store-Standard): ein weicher weißer Schimmer unter der aktuellen und der überfahrenen Marke, damit beide vor bunten Hintergründen lesbar bleiben.',
    takeoverTitle: 'Offizielle Leiste übernehmen',
    takeoverDescription: 'Standardmäßig ein: In der Konversationsansicht ersetzt diese Leiste den offiziellen TurnNavigator am rechten Rand (verborgen, nicht entfernt). Ausschalten, um die Konversationsansicht an die offizielle Leiste zurückzugeben — diese Leiste weicht dort. Die Leseansicht nutzt immer diese Leiste. Bei schmalen Breiten verbirgt der Host die offizielle Leiste selbst; dieser Schalter stellt sie bei ausgeschaltetem Zustand wieder her.',
    colorBarTitle: 'Markierungsfarbe',
    colorAccentTitle: 'Akzentfarbe',
    colorAuto: 'Auto',
    colorCustom: 'Benutzerdefiniert',
    skillTitle: 'generative-mcpapps-Skill',
    skillInstalled: 'Installiert',
    skillMissing: 'Nicht erkannt',
    skillPurpose: 'Diese Installation dient der automatischen Skill-Auswahl für MCP Apps. Der Leser rendert mcp-app-Codeblöcke bereits von selbst, sobald das Modell sie ausgibt.',
    skillPluginNote: 'Das Paket in diesem Plugin-Repository mitzuliefern installiert es nicht in den Skill-Katalog des Harness.',
    skillInstall: 'Kopieren Sie den kompletten Ordner generative-mcpapps (inklusive references und examples) nach .dsh/skills oder .agents/skills — im Home- oder im Projektverzeichnis, wie Sie möchten — und prüfen Sie dann neu. Eine Ein-Klick-Installation, die auf jedem Host funktioniert, gibt es nicht.',
    skillRecheck: 'Neu prüfen',
    skillChecking: 'Wird geprüft…',
    skillUnavailable: 'Der Skill-Katalog des Hosts ließ sich nicht abfragen. Kopieren Sie den Ordner nach .dsh/skills oder .agents/skills (Home oder Projekt) und prüfen Sie neu.',
};
export const it = {
    nav: 'Visualizzazione pulita',
    openTitle: 'Apri i deliverable nel pannello integrato',
    openDescription: 'Disattivato per impostazione predefinita: i chip e i file menzionati si aprono nell’app di sistema. Attiva per visualizzarli in anteprima nella barra laterale destra, come nella chat ufficiale. Mostra file e apri cartella restano sul gestore file di sistema.',
    glassTitle: 'Vetro smerigliato traslucido',
    glassDescription: 'Disattivato per impostazione predefinita: il rivestimento di lettura resta opaco, come nell’aspetto attuale dell’host. Attiva per lasciar trasparire sfondo e temi; i chip di percorso e contatore restano discreti finché non li punti o li selezioni.',
    bubbleTitle: 'Bolle dei messaggi',
    bubbleDescription: 'Attivo per impostazione predefinita: le risposte finali stanno in una bolla arrotondata che le stacca dallo sfondo, traslucida in modalità vetro smerigliato. Disattiva per disporle a piatto sulla pagina.',
    foldTitle: 'Richiudi il processo',
    foldDescription: 'Attivo per impostazione predefinita: i passaggi precedenti si richiudono quando compare un nuovo pensiero. Disattiva per tenere ragionamenti e strumenti sempre espansi.',
    foldNone: 'Off',
    foldStandard: 'On',
    foldSummary: 'Riepilogo',
    railTitle: 'Barra dei messaggi',
    railDescription: 'Attivo per impostazione predefinita: una barra di navigazione in canvas al bordo della conversazione — hover fisheye con riepiloghi, clic per saltare, turno corrente evidenziato. Spenta: nessuna barra nella vista di lettura; la vista conversazione torna alla barra ufficiale.',
    railSide: 'Posizione della barra',
    railSideLeft: 'Bordo sinistro',
    railSideRight: 'Bordo destro (specchiato)',
    railStyle: 'Stile della barra',
    railStyleBar: 'Linee',
    railStyleDot: 'Punti',
    railRingTitle: 'Alone della barra',
    railRingDescription: 'Attivo per impostazione predefinita (come il valore di origine): un delicato alone bianco sotto i segni correnti e puntati, per tenerli leggibili su sfondi molto carichi.',
    takeoverTitle: 'Sostituisci la barra ufficiale',
    takeoverDescription: 'Attivo per impostazione predefinita: nella vista conversazione questa barra sostituisce il TurnNavigator ufficiale sul bordo destro (nascosto, non smontato). Disattiva per restituire la vista conversazione alla barra ufficiale — questa barra cede lì. La vista di lettura usa sempre questa barra. Alle larghezze ridotte l’host nasconde da solo la barra ufficiale; questo interruttore la ripristina quando è disattivato.',
    colorBarTitle: 'Colore dei segni',
    colorAccentTitle: 'Colore d’accento',
    colorAuto: 'Auto',
    colorCustom: 'Personalizzato',
    skillTitle: 'Skill generative-mcpapps',
    skillInstalled: 'Installata',
    skillMissing: 'Non rilevata',
    skillPurpose: 'Questa installazione serve alla selezione automatica delle MCP Apps da parte del modello. Il lettore mostra già i blocchi mcp-app quando il modello li produce.',
    skillPluginNote: 'Distribuire il pacchetto in questo repository di plugin non lo installa nel catalogo skill dell’host.',
    skillInstall: 'Copia l’intera cartella generative-mcpapps (references ed examples inclusi) in .dsh/skills o .agents/skills — nella home o nel progetto, come preferisci — poi ripeti la verifica. Non esiste un’installazione con un clic che funzioni su ogni host.',
    skillRecheck: 'Riverifica',
    skillChecking: 'Verifica in corso…',
    skillUnavailable: 'Impossibile interrogare il catalogo skill dell’host. Copia in .dsh/skills o .agents/skills (home o progetto), poi riverifica.',
};
export const ru = {
    nav: 'Аккуратный вид',
    openTitle: 'Открывать результаты во встроенной панели',
    openDescription: 'По умолчанию выключено: чипы и упоминания файлов открываются в системном приложении. Включите, чтобы смотреть их в правой боковой панели, как в официальном чате. «Показать» и «открыть папку» работают через системный файловый менеджер, как прежде.',
    glassTitle: 'Полупрозрачное матовое стекло',
    glassDescription: 'По умолчанию выключено: обрамление чтения остаётся непрозрачным, как у текущего оформления хоста. Включите, чтобы сквозь панель просвечивали обои и темы; чипы пути и счётчика проступают только при наведении или фокусе.',
    bubbleTitle: 'Пузыри сообщений',
    bubbleDescription: 'По умолчанию включено: финальные ответы ложатся в скруглённый пузырь, отделяющий их от фона; в режиме матового стекла он полупрозрачный. Выключите, чтобы ответы лежали на странице без пузыря.',
    foldTitle: 'Сворачивать процесс',
    foldDescription: 'По умолчанию включено: прежние шаги сворачиваются, когда появляются новые размышления. Выключите, чтобы все рассуждения и инструменты оставались развёрнутыми.',
    foldNone: 'Выкл.',
    foldStandard: 'Вкл.',
    foldSummary: 'Сводка',
    railTitle: 'Дорожка сообщений',
    railDescription: 'По умолчанию включено: навигационная дорожка на canvas у края беседы — «рыбий глаз» при наведении со сводками, переход по клику, подсветка текущего хода. Выключено: в режиме чтения дорожек нет; режим беседы возвращается к штатной дорожке.',
    railSide: 'Положение дорожки',
    railSideLeft: 'Левый край',
    railSideRight: 'Правый край (зеркально)',
    railStyle: 'Стиль дорожки',
    railStyleBar: 'Чёрточки',
    railStyleDot: 'Точки',
    railRingTitle: 'Ореол дорожки',
    railRingDescription: 'По умолчанию включено (совпадает с исходным значением): мягкий белый ореол под текущей и подсвеченной отметками, чтобы их было видно на пёстрых обоях.',
    takeoverTitle: 'Заменить штатную дорожку',
    takeoverDescription: 'По умолчанию включено: в режиме беседы эта дорожка заменяет штатный TurnNavigator у правого края (скрывается, а не удаляется). Выключите, чтобы вернуть режим беседы штатной дорожке — эта дорожка там уступает. Режим чтения всегда использует эту дорожку. На узкой ширине хост скрывает штатную дорожку сам; этот переключатель возвращает её, когда выключен.',
    colorBarTitle: 'Цвет отметок',
    colorAccentTitle: 'Акцентный цвет',
    colorAuto: 'Авто',
    colorCustom: 'Свой',
    skillTitle: 'Навык generative-mcpapps',
    skillInstalled: 'Установлен',
    skillMissing: 'Не обнаружен',
    skillPurpose: 'Эта установка нужна, чтобы модель сама подбирала MCP Apps. Читатель и так показывает блоки mcp-app, когда модель их выводит.',
    skillPluginNote: 'Поставка пакета в репозитории плагина не устанавливает его в каталог навыков хоста.',
    skillInstall: 'Скопируйте всю папку generative-mcpapps (включая references и examples) в .dsh/skills или .agents/skills — в домашнем каталоге или в проекте, как вам удобнее, — и нажмите «Проверить снова». Установки в один клик, работающей на любом хосте, нет.',
    skillRecheck: 'Проверить снова',
    skillChecking: 'Проверяем…',
    skillUnavailable: 'Не удалось опросить каталог навыков хоста. Скопируйте папку в .dsh/skills или .agents/skills (домашний каталог или проект) и проверьте снова.',
};
export const es = {
    nav: 'Vista ordenada',
    openTitle: 'Abrir entregables en el panel integrado',
    openDescription: 'Desactivado por defecto: los chips y los archivos mencionados se abren en la aplicación del sistema. Actívalo para previsualizarlos en la barra lateral derecha, como en el chat oficial. Revelar y abrir la carpeta siguen usando el gestor de archivos del sistema.',
    glassTitle: 'Cristal esmerilado translúcido',
    glassDescription: 'Desactivado por defecto: el marco de lectura sigue opaco, fiel al aspecto actual del host. Actívalo para dejar traslucir el fondo de pantalla y los temas; los chips de ruta y recuento solo se dibujan al pasar el ratón o al enfocar.',
    bubbleTitle: 'Burbujas de mensaje',
    bubbleDescription: 'Activado por defecto: las respuestas finales van en una burbuja redondeada que las separa del fondo, translúcida en modo cristal esmerilado. Desactívalo para colocar las respuestas a plano en la página.',
    foldTitle: 'Plegar el proceso',
    foldDescription: 'Activado por defecto: los pasos anteriores se pliegan cuando aparece un nuevo razonamiento. Desactívalo para mantener todo el pensamiento y todas las herramientas desplegados.',
    foldNone: 'No',
    foldStandard: 'Sí',
    foldSummary: 'Resumen',
    railTitle: 'Raíl de mensajes',
    railDescription: 'Activado por defecto: un raíl de navegación en canvas al borde de la conversación — hover ojo de pez con resúmenes, clic para saltar, turno actual resaltado. Apagado: sin raíl en la vista de lectura; la vista de conversación vuelve al raíl oficial.',
    railSide: 'Posición del raíl',
    railSideLeft: 'Borde izquierdo',
    railSideRight: 'Borde derecho (en espejo)',
    railStyle: 'Estilo del raíl',
    railStyleBar: 'Líneas',
    railStyleDot: 'Puntos',
    railRingTitle: 'Brillo del raíl',
    railRingDescription: 'Activado por defecto (coincide con el valor de fábrica): un suave brillo blanco bajo las marcas actual y apuntada, para que sigan legibles sobre fondos con muchos detalles.',
    takeoverTitle: 'Reemplazar el raíl oficial',
    takeoverDescription: 'Activado por defecto: en la vista de conversación este raíl sustituye al TurnNavigator oficial del borde derecho (oculto, no desmontado). Desactívalo para devolver la vista de conversación al raíl oficial — este raíl cede allí. La vista de lectura siempre usa este raíl. En anchos reducidos el anfitrión oculta el raíl oficial por sí mismo; este interruptor lo restaura cuando está apagado.',
    colorBarTitle: 'Color de las marcas',
    colorAccentTitle: 'Color de acento',
    colorAuto: 'Auto',
    colorCustom: 'Personalizado',
    skillTitle: 'Habilidad generative-mcpapps',
    skillInstalled: 'Instalada',
    skillMissing: 'No detectada',
    skillPurpose: 'Esta instalación sirve para que el modelo elija solo las MCP Apps. El lector ya renderiza los bloques mcp-app cuando el modelo los emite.',
    skillPluginNote: 'Enviar el paquete dentro de este repositorio de plugins no lo instala en el catálogo de habilidades del host.',
    skillInstall: 'Copia la carpeta generative-mcpapps completa (con references y examples) en .dsh/skills o .agents/skills — en tu home o en el proyecto, tú eliges — y vuelve a comprobar. No hay ninguna instalación de un clic que funcione en todos los hosts.',
    skillRecheck: 'Revisar de nuevo',
    skillChecking: 'Comprobando…',
    skillUnavailable: 'No se pudo consultar el catálogo de habilidades del host. Copia en .dsh/skills o .agents/skills (home o proyecto) y vuelve a comprobar.',
};
export const ja = {
    nav: 'すっきり表示',
    openTitle: '成果物を内蔵パネルで開く',
    openDescription: 'デフォルト off：チップや本文内のファイル言及はシステムアプリで開かれます。on にすると公式チャットと同じように右サイドバーでプレビューされます。Finder / エクスプローラー での表示やフォルダーを開く操作はこのスイッチの影響を受けません。',
    glassTitle: '半透明のすりガラス',
    glassDescription: 'デフォルト off：閲覧バーは不透明のままで、現在の Host の見た目と同じです。on にするとホストの壁紙やスキンが透けて見えます。パスや行数のラベルは静止している間は透明のまま、ホバーまたはフォーカスしたときだけ輪郭が出ます。',
    bubbleTitle: 'メッセージバブル',
    bubbleDescription: 'デフォルト on：最終回答は角丸バブルに収まり、ページ背景と区別されます。すりガラス mode では半透明になります。off にすると回答はページにそのまま並びます。',
    foldTitle: 'プロセスを自動折りたたみ',
    foldDescription: 'デフォルト on：新しい思考が出るとそれまでのステップを自動的にたたみます。off にすると思考とツールフローを展開したまま完全に残します。',
    foldNone: 'オフ',
    foldStandard: 'オン',
    foldSummary: '要約',
    railTitle: 'メッセージレール',
    railDescription: 'デフォルト on：会話領域の縁に canvas のナビゲーションレールを表示——フィッシュアイホバーで要約、クリックで移動、現在のターンをハイライト。',
    railSide: '表示位置',
    railSideLeft: '左端',
    railSideRight: '右端（ミラー）',
    railStyle: '表示スタイル',
    railStyleBar: '横線',
    railStyleDot: 'ドット',
    railRingTitle: '外側のやわらかい光',
    railRingDescription: 'デフォルト on：現在のターンとホバー中のターンの目印の下に白いやわらかい光を敷き、複雑な壁紙でも目印を読みやすくします。',
    takeoverTitle: '公式メッセージレールを代行',
    takeoverDescription: 'デフォルト on：公式の右端 TurnNavigator を非表示にします（アンマウントではなく非表示）ので、このレールだけが残り、off にすると両方のレールが出ます。',
    colorBarTitle: '目印の色',
    colorAccentTitle: 'アクセントカラー',
    colorAuto: '自動',
    colorCustom: 'カスタム',
    skillTitle: 'generative-mcpapps スキル',
    skillInstalled: 'インストール済み',
    skillMissing: '未検出',
    skillPurpose: 'このインストールは、モデルが MCP Apps を自動選択するためのものです。読み取りビューはモデルが mcp-app コードブロックを出力した時点で描画するため、スキルのホストインストール有無には依存しません。',
    skillPluginNote: 'スキルパックがこのプラグイン リポジトリに同梱されていることは、現在の Agent に読み込まれていることとは別です。',
    skillInstall: 'generative-mcpapps フォルダー全体（references と examples を含む）を .dsh/skills または .agents/skills（ホームでもプロジェクトでも、お好みで）へコピーし、その後にもう一度検出してください。すべてのホストで動くワンクリックインストールはありません。',
    skillRecheck: '再検出',
    skillChecking: '検出中…',
    skillUnavailable: 'ホストのスキルカタログを照会できませんでした。.dsh/skills または .agents/skills（ホームまたはプロジェクト）へコピーして、もう一度検出してください。',
};
export const ko = {
    nav: '깔끔한 보기',
    openTitle: '산출물을 내장 패널에서 열기',
    openDescription: '기본 끔: 칩과 본문 안의 파일 언급은 시스템 앱으로 열립니다. 켜면 공식 대화와 마찬가지로 오른쪽 사이드바에 미리 봅니다. Finder / 탐색기의 표시나 폴더 열기는 이 스위치의 영향을 받지 않습니다.',
    glassTitle: '반투명 뿌연 유리',
    glassDescription: '기본 끔: 읽기 막대는 불투명한 그대로, 현재 Host 의 느낌과 같습니다. 켜면 호스트 배경화면과 스킨이 비칩니다. 경로, 줄 수 같은 라벨은 가만히 있을 때는 투명하고, 호버 또는 포커스해야 윤곽이 나타납니다.',
    bubbleTitle: '메시지 말풍선',
    bubbleDescription: '기본 켬: 최종 답변을 둥근 말풍선에 담아 페이지 배경과 구분합니다. 뿌연 유리 모드에서는 반투명이 됩니다. 끄면 답변이 페이지에 그대로 펼쳐집니다.',
    foldTitle: '과정 자동 접기',
    foldDescription: '기본 켬: 새 사고가 생성되면 이전 단계를 자동으로 접습니다. 끄면 끝까지 펼쳐 두고 원본 사고와 도구 흐름을 그대로 남깁니다.',
    foldNone: '끔',
    foldStandard: '켬',
    foldSummary: '요약',
    railTitle: '메시지 레일',
    railDescription: '기본 켬: 대화 영역 가장자리의 canvas 탐색 레일 — 물고기눈 호버로 요약 보기, 클릭으로 이동, 현재 턴 강조.',
    railSide: '표시 위치',
    railSideLeft: '왼쪽 끝',
    railSideRight: '오른쪽 끝 (반전)',
    railStyle: '표시 스타일',
    railStyleBar: '가로선',
    railStyleDot: '점',
    railRingTitle: '바깥 고리 은은한 빛',
    railRingDescription: '기본 켬: 현재 턴과 호버 중인 턴의 표시 아래에 흰색 은은한 빛을 깔아 복잡한 배경화면에서도 표시를 읽기 쉽게 합니다.',
    takeoverTitle: '공식 메시지 레일 대체',
    takeoverDescription: '기본 켬: 공식 오른쪽 끝 TurnNavigator 를 숨깁니다(제거가 아니라 숨김). 이 레일만 남기고, 끄면 두 레일이 함께 나타납니다.',
    colorBarTitle: '표시 색',
    colorAccentTitle: '강조 색',
    colorAuto: '자동',
    colorCustom: '사용자 지정',
    skillTitle: 'generative-mcpapps 스킬',
    skillInstalled: '설치됨',
    skillMissing: '감지되지 않음',
    skillPurpose: '이 설치는 모델이 MCP Apps 를 자동으로 고르도록 하기 위한 것입니다. 읽기 뷰는 모델이 mcp-app 코드 블록을 출력하면 이미 렌더링하므로, 스킬의 호스트 설치 여부에 의존하지 않습니다.',
    skillPluginNote: '스킬 패키지가 이 플러그인 저장소에 포함되어 있는 것은, 현재 Agent 가 이를 로드했다는 뜻이 아닙니다.',
    skillInstall: 'generative-mcpapps 폴더 전체(references 와 examples 포함)를 .dsh/skills 또는 .agents/skills(홈이나 프로젝트, 직접 선택)에 복사한 뒤 다시 감지하세요. 모든 호스트에서 되는 원클릭 설치는 없습니다.',
    skillRecheck: '다시 감지',
    skillChecking: '감지 중…',
    skillUnavailable: '호스트 스킬 카탈로그를 조회할 수 없습니다. .dsh/skills 또는 .agents/skills(홈 또는 프로젝트)에 복사한 뒤 다시 감지하세요.',
};
const dictionaries = { zh, en, ja, ko, fr, de, it, ru, es };
const languageByPrefix = [
    ['zh', 'zh'], ['en', 'en'], ['ja', 'ja'], ['ko', 'ko'], ['fr', 'fr'], ['de', 'de'], ['it', 'it'], ['ru', 'ru'], ['es', 'es'],
];
export function settingsLanguage(tag) {
    const lower = (tag ?? '').toLowerCase();
    for (const [prefix, language] of languageByPrefix) {
        if (lower.startsWith(prefix))
            return language;
    }
    return 'en';
}
export function settingsCopyFor(tag) {
    return dictionaries[settingsLanguage(tag)];
}
//# sourceMappingURL=settings-copy.js.map