/**
 * sync-hosts.mjs —— 从 hosts.mjs（唯一事实源）下发本仓全部宿主声明写点。
 *
 * 改编自 dsh-date-wrapper/scripts/sync-hosts.mjs（P0 试点定型版），本仓差异：
 * 1. 写点 1 = package.json：engines.dsh + **12 个 dsh-* peer**（全量枚举，optional
 *    ——profile 安装 autoInstallPeers:false，peer 不经注册表解析；optional 只影响
 *    独立 npm 安装的开发场景）+ cordis peer（^4.0.2 横跨两代 cordis 线）；
 *    `react` 为上游生态 peer，不属于宿主声明面，本脚本不碰。
 * 2. 写点 2 = dsh.plugin.json：本仓**没有**插件 manifest（findings §1.2）——存在
 *    才管理（engines.dsh + version 镜像），不存在跳过不报错（INDEX §C 写点全景）。
 * 3. 写点 3 = **七语 README** 管理块（README.md 为简体中文 + en/de/es/fr/it/ru）。
 *
 * 双模式：默认只校验（exit 1 = 有漂移）；`--write` 实际写盘。
 * 用法：node scripts/sync-hosts.mjs [--write]
 */
import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import assert from 'node:assert/strict'
import { supportedHosts, peerRange, developmentHost, hostPeerPackages, cordisRange } from './hosts.mjs'

const ROOT = new URL('..', import.meta.url)
const write = process.argv.includes('--write')
const read = (rel) => readFile(new URL(rel, ROOT), 'utf8')

// ── 0. hosts.mjs 自检 ────────────────────────────────────────────────────────
const RC_RE = /^\d+\.\d+\.\d+-rc\.\d+$/
assert(supportedHosts.length > 0, 'supportedHosts 不得为空')
assert.equal(new Set(supportedHosts).size, supportedHosts.length, 'supportedHosts 有重复项')
for (const v of supportedHosts) assert(RC_RE.test(v), `非 rc 版本混入枚举: ${v}（本插件只收 rc）`)
assert(supportedHosts.includes(developmentHost), 'developmentHost 必须在 supportedHosts 内')
assert(hostPeerPackages.length > 0, 'hostPeerPackages 不得为空')

// ── 1. package.json：engines.dsh + 12 个 dsh-* peer + cordis peer ────────────
const pkgUrl = new URL('package.json', ROOT)
const pkgOriginal = await read('package.json')
const pkg = JSON.parse(pkgOriginal)
pkg.engines ??= {}
pkg.engines.dsh = peerRange
pkg.peerDependencies ??= {}
pkg.peerDependenciesMeta ??= {}
for (const name of hostPeerPackages) {
  pkg.peerDependencies[name] = peerRange
  // optional：宿主 peer 闸（app-boot evaluatePluginCompatibility）照样逐项比对外来
  // 版本；meta 只影响独立 npm 安装场景——缺失不拦安装（fail-soft 与运行时姿态
  // 一致：webServer/skills/webServer 路由全有守卫）。树内一旦存在但版本不在枚举，
  // npm/pnpm 照样 ERESOLVE。
  pkg.peerDependenciesMeta[name] = { optional: true }
}
pkg.peerDependencies['@deepseek-ai/cordis'] = cordisRange
delete pkg.peerDependenciesMeta['@deepseek-ai/cordis']
const pkgExpected = JSON.stringify(pkg, null, 2) + '\n'

// ── 2. dsh.plugin.json（存在才管理）：engines.dsh + manifest version 镜像 ─────
const pluginJsonUrl = new URL('dsh.plugin.json', ROOT)
const hasManifest = existsSync(pluginJsonUrl)
let manifestOriginal, manifestExpected
if (hasManifest) {
  manifestOriginal = await read('dsh.plugin.json')
  const manifest = JSON.parse(manifestOriginal)
  manifest.engines ??= {}
  manifest.engines.dsh = peerRange
  manifest.version = pkg.version // version 以 package.json 为准，manifest 只镜像
  manifestExpected = JSON.stringify(manifest, null, 2) + '\n'
}

// ── 3. 七语 README：管理块（支持清单 + 运行时已验证清单） ────────────────────
const BEGIN = '<!-- host-compat:begin — generated by scripts/sync-hosts.mjs from scripts/hosts.mjs; DO NOT EDIT -->'
const END = '<!-- host-compat:end -->'
const versionList = supportedHosts.map((v) => `\`${v}\``).join(' ')
const LINES = '0.1.0 / 0.1.1 / 0.1.2 / 0.1.5 / 0.1.7 / 0.2.0'
const linesPerLang = {
  'README.md': [
    `- **支持的 DSH 宿主：** ${versionList}（覆盖 ${LINES} 六条线共 ${supportedHosts.length} 个 rc）`,
  ],
  'README.en.md': [
    `- **Supported DSH hosts:** ${versionList} (${supportedHosts.length} rc releases across lines ${LINES})`,
  ],
  'README.de.md': [
    `- **Unterstützte DSH-Hosts:** ${versionList} (${supportedHosts.length} RC über die Linien ${LINES})`,
  ],
  'README.es.md': [
    `- **Hosts DSH compatibles:** ${versionList} (${supportedHosts.length} rc en las líneas ${LINES})`,
  ],
  'README.fr.md': [
    `- **Hôtes DSH pris en charge :** ${versionList} (${supportedHosts.length} rc sur les lignes ${LINES})`,
  ],
  'README.it.md': [
    `- **Host DSH supportati:** ${versionList} (${supportedHosts.length} rc attraverso le linee ${LINES})`,
  ],
  'README.ru.md': [
    `- **Поддерживаемые хосты DSH:** ${versionList} (${supportedHosts.length} rc по линиям ${LINES})`,
  ],
}
// 矩阵跑绿清单（.compat-results/verified.json，由 scripts/test-host-compat.mjs 写出）
const verifiedUrl = new URL('.compat-results/verified.json', ROOT)
if (existsSync(verifiedUrl)) {
  const { verified = [] } = JSON.parse(await readFile(verifiedUrl, 'utf8'))
  if (verified.length > 0) {
    const list = verified.map((v) => `\`${v}\``).join(', ')
    const verifiedLine = {
      'README.md': `- **运行时已验证：** ${list}（证据见 \`.compat-results/\`）`,
      'README.en.md': `- **Runtime-verified:** ${list} — evidence in \`.compat-results/\``,
      'README.de.md': `- **Zur Laufzeit verifiziert:** ${list} — Nachweise in \`.compat-results/\``,
      'README.es.md': `- **Verificado en tiempo de ejecución:** ${list} — evidencia en \`.compat-results/\``,
      'README.fr.md': `- **Vérifié à l'exécution :** ${list} — preuves dans \`.compat-results/\``,
      'README.it.md': `- **Verificato a runtime:** ${list} — prove in \`.compat-results/\``,
      'README.ru.md': `- **Проверено на этапе выполнения:** ${list} — доказательства в \`.compat-results/\``,
    }
    for (const [file, line] of Object.entries(verifiedLine)) linesPerLang[file].push(line)
  }
}
const readmeProblems = []
for (const [file, lines] of Object.entries(linesPerLang)) {
  const block = `${BEGIN}\n${lines.join('\n')}\n${END}`
  const url = new URL(file, ROOT)
  const content = await readFile(url, 'utf8')
  const beginAt = content.indexOf(BEGIN)
  if (beginAt === -1) {
    // 插入点：第一个 `## ` 二级标题前（七语结构一致）
    const at = content.search(/^## /m)
    assert(at !== -1, `${file} 找不到插入锚点（第一个二级标题）`)
    if (write) {
      await writeFile(url, content.slice(0, at) + block + '\n\n' + content.slice(at))
      console.log(`write  ${file}: 插入管理块`)
    } else {
      readmeProblems.push(`${file} 缺少 host-compat 管理块`)
    }
    continue
  }
  const endAt = content.indexOf(END, beginAt)
  assert(endAt !== -1, `${file} 管理块缺少 end 标记`)
  const current = content.slice(beginAt, endAt + END.length)
  if (write) {
    if (current !== block) {
      await writeFile(url, content.slice(0, beginAt) + block + content.slice(endAt + END.length))
      console.log(`write  ${file}: 更新管理块`)
    } else {
      console.log(`ok     ${file}: 管理块已是最新`)
    }
  } else if (current !== block) {
    readmeProblems.push(`${file} 管理块内容需要同步`)
  } else {
    console.log(`ok     ${file}: 管理块已是最新`)
  }
}

// ── 4. 汇总校验/写盘 ────────────────────────────────────────────────────────
if (write) {
  if (pkgOriginal !== pkgExpected) {
    await writeFile(pkgUrl, pkgExpected)
    console.log('write  package.json (engines.dsh + 12 dsh-* peers + cordis)')
  } else console.log('ok     package.json')
  if (hasManifest) {
    if (manifestOriginal !== manifestExpected) {
      await writeFile(pluginJsonUrl, manifestExpected)
      console.log('write  dsh.plugin.json (engines.dsh + version)')
    } else console.log('ok     dsh.plugin.json')
  } else console.log('skip   dsh.plugin.json（本仓无插件 manifest）')
  console.log('done   --write 完成')
} else {
  const jsonDrift = pkgOriginal !== pkgExpected ? ['package.json (engines.dsh / peerDependencies / cordis)'] : []
  if (hasManifest && manifestOriginal !== manifestExpected) jsonDrift.push('dsh.plugin.json (engines.dsh / version)')
  if (jsonDrift.length === 0 && readmeProblems.length === 0) {
    console.log('ok     全部写点与 hosts.mjs 一致')
  } else {
    for (const p of [...jsonDrift, ...readmeProblems]) console.error(`drift  ${p}`)
    console.error('\n运行 node scripts/sync-hosts.mjs --write 修复')
    process.exit(1)
  }
}
